// <auto-generated />
using System;
using HansPortfolio.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HansPortfolio.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    partial class PortfolioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("portfolio")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HansPortfolio.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Highlight")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("SummaryEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SummaryPt")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("customers", "portfolio");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionPt")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("Highlight")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("SummaryEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SummaryPt")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TitlePt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("experiences", "portfolio");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.ExperienceCustomer", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.HasKey("ExperienceId", "CustomerId");

                    b.HasIndex("CustomerId");

                    b.ToTable("experience_customers", "portfolio");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.ExperienceImageAsset", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ImageAssetId")
                        .HasColumnType("uuid");

                    b.HasKey("ExperienceId", "ImageAssetId");

                    b.HasIndex("ImageAssetId");

                    b.ToTable("experience_image_assets", "portfolio");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.ExperienceJob", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.HasKey("ExperienceId", "JobId");

                    b.HasIndex("JobId");

                    b.ToTable("experience_jobs", "portfolio");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.ExperienceLink", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LinkId")
                        .HasColumnType("uuid");

                    b.HasKey("ExperienceId", "LinkId");

                    b.HasIndex("LinkId");

                    b.ToTable("experience_links", "portfolio");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.ExperienceTechnology", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TechnologyId")
                        .HasColumnType("uuid");

                    b.HasKey("ExperienceId", "TechnologyId");

                    b.HasIndex("TechnologyId");

                    b.ToTable("experience_technologies", "portfolio");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.Formation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DegreeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("Highlight")
                        .HasColumnType("boolean");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("SummaryEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SummaryPt")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TitlePt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("formations", "portfolio");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.FormationImageAsset", b =>
                {
                    b.Property<Guid>("FormationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ImageAssetId")
                        .HasColumnType("uuid");

                    b.HasKey("FormationId", "ImageAssetId");

                    b.HasIndex("ImageAssetId");

                    b.ToTable("formation_image_assets", "portfolio");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.FormationLink", b =>
                {
                    b.Property<Guid>("FormationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LinkId")
                        .HasColumnType("uuid");

                    b.HasKey("FormationId", "LinkId");

                    b.HasIndex("LinkId");

                    b.ToTable("formation_links", "portfolio");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.FormationTechnology", b =>
                {
                    b.Property<Guid>("FormationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TechnologyId")
                        .HasColumnType("uuid");

                    b.HasKey("FormationId", "TechnologyId");

                    b.HasIndex("TechnologyId");

                    b.ToTable("formation_technologies", "portfolio");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.ImageAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AltEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AltPt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CaptionEn")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CaptionPt")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("image_assets", "portfolio");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Highlight")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NamePt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("SummaryEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SummaryPt")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("jobs", "portfolio");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DescriptionPt")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("LabelEn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("LabelPt")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("links", "portfolio");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.PortfolioSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("portfolio_settings", "portfolio");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeployUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DocsUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Featured")
                        .HasColumnType("boolean");

                    b.Property<string>("FullDescriptionEn")
                        .HasColumnType("text");

                    b.Property<string>("FullDescriptionPt")
                        .HasColumnType("text");

                    b.Property<bool>("Highlight")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("NpmUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RepositoryUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ShortDescriptionEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ShortDescriptionPt")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TitlePt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("projects", "portfolio");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.ProjectExperience", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid");

                    b.HasKey("ProjectId", "ExperienceId");

                    b.HasIndex("ExperienceId");

                    b.ToTable("project_experiences", "portfolio");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.ProjectImageAsset", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ImageAssetId")
                        .HasColumnType("uuid");

                    b.HasKey("ProjectId", "ImageAssetId");

                    b.HasIndex("ImageAssetId");

                    b.ToTable("project_image_assets", "portfolio");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.ProjectLink", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LinkId")
                        .HasColumnType("uuid");

                    b.HasKey("ProjectId", "LinkId");

                    b.HasIndex("LinkId");

                    b.ToTable("project_links", "portfolio");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.ProjectTag", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("ProjectId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("project_tags", "portfolio");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.ProjectTechnology", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TechnologyId")
                        .HasColumnType("uuid");

                    b.HasKey("ProjectId", "TechnologyId");

                    b.HasIndex("TechnologyId");

                    b.ToTable("project_technologies", "portfolio");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.SpokenLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("Highlight")
                        .HasColumnType("boolean");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NamePt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Proficiency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("spoken_languages", "portfolio");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NamePt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tags", "portfolio");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.Technology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Highlight")
                        .HasColumnType("boolean");

                    b.Property<string>("Icon")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("OfficialUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsageContexts")
                        .HasColumnType("integer");

                    b.Property<string>("UsageFrequency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("technologies", "portfolio");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.TechnologyTag", b =>
                {
                    b.Property<Guid>("TechnologyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("TechnologyId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("technology_tags", "portfolio");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", "portfolio");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.ExperienceCustomer", b =>
                {
                    b.HasOne("HansPortfolio.Domain.Entities.Customer", "Customer")
                        .WithMany("ExperienceCustomers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HansPortfolio.Domain.Entities.Experience", "Experience")
                        .WithMany("ExperienceCustomers")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.ExperienceImageAsset", b =>
                {
                    b.HasOne("HansPortfolio.Domain.Entities.Experience", "Experience")
                        .WithMany("ExperienceImageAssets")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HansPortfolio.Domain.Entities.ImageAsset", "ImageAsset")
                        .WithMany("ExperienceImageAssets")
                        .HasForeignKey("ImageAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");

                    b.Navigation("ImageAsset");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.ExperienceJob", b =>
                {
                    b.HasOne("HansPortfolio.Domain.Entities.Experience", "Experience")
                        .WithMany("ExperienceJobs")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HansPortfolio.Domain.Entities.Job", "Job")
                        .WithMany("ExperienceJobs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.ExperienceLink", b =>
                {
                    b.HasOne("HansPortfolio.Domain.Entities.Experience", "Experience")
                        .WithMany("ExperienceLinks")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HansPortfolio.Domain.Entities.Link", "Link")
                        .WithMany("ExperienceLinks")
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");

                    b.Navigation("Link");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.ExperienceTechnology", b =>
                {
                    b.HasOne("HansPortfolio.Domain.Entities.Experience", "Experience")
                        .WithMany("ExperienceTechnologies")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HansPortfolio.Domain.Entities.Technology", "Technology")
                        .WithMany("ExperienceTechnologies")
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.FormationImageAsset", b =>
                {
                    b.HasOne("HansPortfolio.Domain.Entities.Formation", "Formation")
                        .WithMany("FormationImageAssets")
                        .HasForeignKey("FormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HansPortfolio.Domain.Entities.ImageAsset", "ImageAsset")
                        .WithMany("FormationImageAssets")
                        .HasForeignKey("ImageAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formation");

                    b.Navigation("ImageAsset");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.FormationLink", b =>
                {
                    b.HasOne("HansPortfolio.Domain.Entities.Formation", "Formation")
                        .WithMany("FormationLinks")
                        .HasForeignKey("FormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HansPortfolio.Domain.Entities.Link", "Link")
                        .WithMany("FormationLinks")
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formation");

                    b.Navigation("Link");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.FormationTechnology", b =>
                {
                    b.HasOne("HansPortfolio.Domain.Entities.Formation", "Formation")
                        .WithMany("FormationTechnologies")
                        .HasForeignKey("FormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HansPortfolio.Domain.Entities.Technology", "Technology")
                        .WithMany("FormationTechnologies")
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formation");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.ProjectExperience", b =>
                {
                    b.HasOne("HansPortfolio.Domain.Entities.Experience", "Experience")
                        .WithMany("ProjectExperiences")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HansPortfolio.Domain.Entities.Project", "Project")
                        .WithMany("ProjectExperiences")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.ProjectImageAsset", b =>
                {
                    b.HasOne("HansPortfolio.Domain.Entities.ImageAsset", "ImageAsset")
                        .WithMany("ProjectImageAssets")
                        .HasForeignKey("ImageAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HansPortfolio.Domain.Entities.Project", "Project")
                        .WithMany("ProjectImageAssets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageAsset");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.ProjectLink", b =>
                {
                    b.HasOne("HansPortfolio.Domain.Entities.Link", "Link")
                        .WithMany("ProjectLinks")
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HansPortfolio.Domain.Entities.Project", "Project")
                        .WithMany("ProjectLinks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Link");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.ProjectTag", b =>
                {
                    b.HasOne("HansPortfolio.Domain.Entities.Project", "Project")
                        .WithMany("ProjectTags")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HansPortfolio.Domain.Entities.Tag", "Tag")
                        .WithMany("ProjectTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.ProjectTechnology", b =>
                {
                    b.HasOne("HansPortfolio.Domain.Entities.Project", "Project")
                        .WithMany("ProjectTechnologies")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HansPortfolio.Domain.Entities.Technology", "Technology")
                        .WithMany("ProjectTechnologies")
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.TechnologyTag", b =>
                {
                    b.HasOne("HansPortfolio.Domain.Entities.Tag", "Tag")
                        .WithMany("TechnologyTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HansPortfolio.Domain.Entities.Technology", "Technology")
                        .WithMany("TechnologyTags")
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.Customer", b =>
                {
                    b.Navigation("ExperienceCustomers");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.Experience", b =>
                {
                    b.Navigation("ExperienceCustomers");

                    b.Navigation("ExperienceImageAssets");

                    b.Navigation("ExperienceJobs");

                    b.Navigation("ExperienceLinks");

                    b.Navigation("ExperienceTechnologies");

                    b.Navigation("ProjectExperiences");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.Formation", b =>
                {
                    b.Navigation("FormationImageAssets");

                    b.Navigation("FormationLinks");

                    b.Navigation("FormationTechnologies");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.ImageAsset", b =>
                {
                    b.Navigation("ExperienceImageAssets");

                    b.Navigation("FormationImageAssets");

                    b.Navigation("ProjectImageAssets");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.Job", b =>
                {
                    b.Navigation("ExperienceJobs");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.Link", b =>
                {
                    b.Navigation("ExperienceLinks");

                    b.Navigation("FormationLinks");

                    b.Navigation("ProjectLinks");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.Project", b =>
                {
                    b.Navigation("ProjectExperiences");

                    b.Navigation("ProjectImageAssets");

                    b.Navigation("ProjectLinks");

                    b.Navigation("ProjectTags");

                    b.Navigation("ProjectTechnologies");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.Tag", b =>
                {
                    b.Navigation("ProjectTags");

                    b.Navigation("TechnologyTags");
                });

            modelBuilder.Entity("HansPortfolio.Domain.Entities.Technology", b =>
                {
                    b.Navigation("ExperienceTechnologies");

                    b.Navigation("FormationTechnologies");

                    b.Navigation("ProjectTechnologies");

                    b.Navigation("TechnologyTags");
                });
#pragma warning restore 612, 618
        }
    }
}
